(function(){
  const form=document.getElementById('quizForm');if(!form)return;
  const steps=[...document.querySelectorAll('.quiz-step')],next=document.getElementById('quizNext'),back=document.getElementById('quizBack'),status=document.getElementById('quizStatus'),bar=document.getElementById('quizProgress'),progressText=document.getElementById('quizProgressText');let step=0;form.dataset.readyAt=String(Date.now());
  const contactValid=v=>/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i.test(v.trim())||v.replace(/\D/g,'').length>=10||/^@[\w]{5,}$/.test(v.trim());
  function render(){steps.forEach((el,i)=>el.hidden=i!==step);back.hidden=step===0;next.textContent=step===steps.length-1?'Получить расчёт':'Далее';bar.style.width=`${((step+1)/steps.length)*100}%`;progressText.textContent=`Шаг ${step+1} из ${steps.length}`;status.textContent='';}
  function valid(){if(step<4){const inputs=[...steps[step].querySelectorAll('input')];if(!inputs.some(i=>i.checked)){status.textContent='Выберите хотя бы один вариант.';return false;}}else{if(form.elements.name.value.trim().length<2||!contactValid(form.elements.contact.value)||!form.elements.consent.checked){status.textContent='Проверьте имя, контакт и согласие.';return false;}}return true;}
  next.addEventListener('click',()=>{if(!valid())return;if(step<steps.length-1){step++;render();return;}if(form.elements.website.value)return;const last=Number(localStorage.getItem('novatechLastSubmit:calculator')||0);if(Date.now()-last<30000){status.textContent='Повторный расчёт можно сохранить через 30 секунд.';return;}const data=new FormData(form);let base=Number(data.get('type')||0)+Number(data.get('design')||0);data.getAll('features').forEach(v=>base+=Number(v));base=Math.round(base*Number(data.get('speed')||1)/10000)*10000;const number=`CALC-${Date.now().toString().slice(-8)}`;const saved=JSON.parse(localStorage.getItem('novatechCalculations')||'[]');saved.push({number,price:base,name:data.get('name'),contact:data.get('contact'),createdAt:new Date().toISOString()});localStorage.setItem('novatechCalculations',JSON.stringify(saved.slice(-20)));localStorage.setItem('novatechLastSubmit:calculator',String(Date.now()));form.hidden=true;document.getElementById('quizResult').hidden=false;document.getElementById('quizPrice').textContent=`от ${base.toLocaleString('ru-RU')} ₽`;document.getElementById('quizSummary').textContent=`Расчёт № ${number}`;});
  back.addEventListener('click',()=>{if(step>0){step--;render();}});render();
})();
